#!/usr/bin/env python3
"""Fill in contributor profiles from GitHub, at build time.

contributors.json holds only what GitHub cannot know: the handle, and optional overrides.
Everything else - display name, avatar, bio, location, LinkedIn - is read from the GitHub
profile and written to contributors.generated.json, which is what the site renders.

Avatars are downloaded and served from our own origin on purpose:

  * the page's CSP stays img-src 'self' data:, with no third-party image sources
  * no visitor's IP address is handed to github.com just to render a face
  * nothing shifts or breaks if github.com is slow, and the page works offline

Anything a contributor sets in contributors.json wins over GitHub, so a stale profile
bio never overrides a deliberate one.

  GITHUB_TOKEN=... python3 scripts/sync_contributors.py      # 5000 req/hr
  python3 scripts/sync_contributors.py                       # 60 req/hr, fine for now
"""
import json, os, pathlib, subprocess, sys, urllib.request, urllib.error

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'public/data/contributors.json'
OUT = ROOT / 'public/data/contributors.generated.json'
AVATARS = ROOT / 'public/avatars'
UA = {'User-Agent': 'weteachkubernetes-site'}
SIZE = 160

# fields a contributor may set themselves; these always beat the GitHub profile
OVERRIDABLE = ('name', 'pronouns', 'title', 'location', 'tz', 'linkedin', 'certs', 'teaches')


def token():
    t = os.environ.get('GITHUB_TOKEN') or os.environ.get('GH_TOKEN')
    if t:
        return t
    try:                              # local convenience: borrow the gh CLI session
        return subprocess.run(['gh', 'auth', 'token'], capture_output=True, text=True,
                              timeout=10).stdout.strip() or None
    except Exception:
        return None


def api(path, tok):
    h = dict(UA, Accept='application/vnd.github+json')
    if tok:
        h['Authorization'] = f'Bearer {tok}'
    req = urllib.request.Request(f'https://api.github.com{path}', headers=h)
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def fetch_avatar(handle, url):
    AVATARS.mkdir(parents=True, exist_ok=True)
    dest = AVATARS / f'{handle.lower()}.png'
    req = urllib.request.Request(f'{url}&s={SIZE}' if '?' in url else f'{url}?s={SIZE}',
                                 headers=UA)
    with urllib.request.urlopen(req, timeout=20) as r:
        data = r.read()
    if not data.startswith((b'\x89PNG', b'\xff\xd8')):     # png or jpeg, nothing else
        raise ValueError('not an image')
    dest.write_bytes(data)
    return f'/avatars/{dest.name}', len(data)


def main():
    src = json.loads(SRC.read_text())
    tok = token()
    print('github api:', 'authenticated' if tok else 'anonymous (60 req/hr)')

    people, failed = [], []
    for entry in src['people']:
        handle = entry['handle']
        person = {'handle': handle, 'github': f'https://github.com/{handle}'}
        try:
            gh = api(f'/users/{handle}', tok)
        except urllib.error.HTTPError as e:
            print(f'  {handle}: profile unavailable ({e.code}) - using local fields only')
            failed.append(handle)
            gh = {}

        # GitHub first, then let the local file override it
        person['name'] = gh.get('name') or handle
        person['bio'] = (gh.get('bio') or '').strip() or None
        person['location'] = gh.get('location')
        person['company'] = gh.get('company')
        person['public_repos'] = gh.get('public_repos')
        blog = (gh.get('blog') or '').strip()
        if 'linkedin.com/' in blog:
            person['linkedin'] = blog
        elif blog:
            person['site'] = blog
        person['avatar'] = None

        if gh.get('avatar_url'):
            try:
                person['avatar'], n = fetch_avatar(handle, gh['avatar_url'])
                print(f'  {handle}: {person["name"]} · avatar {n}b -> {person["avatar"]}')
            except Exception as e:
                print(f'  {handle}: avatar failed ({e}) - the generated portrait will be used')

        for k in OVERRIDABLE:
            if entry.get(k) not in (None, '', [], {}):
                person[k] = entry[k]
        people.append({k: v for k, v in person.items() if v not in (None, '', [], {})})

    OUT.write_text(json.dumps({
        '_note': 'GENERATED by scripts/sync_contributors.py. Do not edit; edit '
                 'contributors.json and re-run. Profile fields come from the GitHub API and '
                 'avatars are mirrored into public/avatars/ so the page loads no third-party '
                 'images.',
        '_source': 'public/data/contributors.json',
        'people': people,
    }, indent=2, ensure_ascii=False) + '\n')

    print(f'\nwrote {OUT.relative_to(ROOT)}: {len(people)} people, '
          f'{sum(1 for p in people if p.get("avatar"))} with a real avatar')
    if failed:
        print('profiles that could not be read:', ', '.join(failed))


if __name__ == '__main__':
    main()
